name: Install eitprocessing
description: Install eitprocessing on the given Python version.
inputs:
  python-version:
    description: "The Python version to use"
    required: false
    default: "3.10"
  dependencies:
    description: "The optional dependencies of eitprocessing to install"
    required: false
  extract-data:
    description: "Whether to extract testing data"
    required: false
    default: "false"
  token:
    description: "GitHub TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Set data dir
      shell: bash
      if: ${{ inputs.extract-data == 'true' }}
      id: set-path
      run: echo "data_dir=$GITHUB_WORKSPACE/test_data" >> "$GITHUB_OUTPUT"
    - name: Restore dataset cache
      if: ${{ inputs.extract-data == 'true' }}
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-path.outputs.data_dir }}
        key: testdata-zenodo-10.5281/zenodo.17423608
    - name: Download test dataset
      shell: bash
      if: inputs.extract-data == 'true' && steps.cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ steps.set-path.outputs.data_dir }}
        wget -q -O ${{ steps.set-path.outputs.data_dir }}/eitprocessing_test_data.zip https://zenodo.org/api/records/17423608/files-archive?download=1
        unzip ${{ steps.set-path.outputs.data_dir }}/eitprocessing_test_data.zip -d ${{ steps.set-path.outputs.data_dir }}
    - uses: actions/cache@v4
      id: cache-python-env
      with:
        path: ~/.cache/pip
        key: ${{ inputs.python-version }}-${{ hashFiles('pyproject.toml') }}-[${{ inputs.dependencies }}]
    - name: Install eitprocessing with [${{ inputs.dependencies }}] dependencies
      run: python3 -m pip install ".[${{ inputs.dependencies }}]"
      shell: bash
