site_name: eitprocessing
site_description: ALIVE project
strict: false

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: darkblue
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: darkblue
      accent: pink
      toggle:
        icon: material/weather-night
        name: "Switch to light mode"
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    logo: "material/home"
    next: fontawesome/solid/angle-right
    previous: fontawesome/solid/angle-left
    repo: fontawesome/brands/github-alt
    view: material/eye

repo_url: https://github.com/EIT-ALIVE/eitprocessing
repo_name: EIT-ALIVE/eitprocessing
edit_uri: edit/main/docs/

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - installation.md
      - Example Notebooks:
        - examples/notebooks/test_ratedetection.ipynb
        - examples/notebooks/test_plot_filter_results.ipynb
        - examples/notebooks/test_watershed.ipynb
  - API Documentation:
      - api/loading.md
      - Data Containers:
        - Sequence: api/datacontainers/sequence.md
        - EITData: api/datacontainers/eitdata.md
        - ContinuousData: api/datacontainers/continuousdata.md
        - SparseData: api/datacontainers/sparsedata.md
        - IntervalData: api/datacontainers/intervaldata.md
        - PixelMap: api/datacontainers/pixelmap.md
        - Breath: api/datacontainers/breath.md
        - Event: api/datacontainers/event.md
        - DataCollection: api/datacontainers/datacollection.md
      - Features:
        - Breath Detection: api/features/breath_detection.md
        - Pixel Breath: api/features/pixel_breath.md
        - Rate Detection: api/features/rate_detection.md
        - Moving Average: api/features/moving_average.md
      - Filters:
        - Butterworth filters: api/filters/butterworth.md
        - MDN filter: api/filters/mdn.md
      - Regions of Interest:
        - Regions of Interest: api/roi/roi.md
        - FilterROIBySize: api/roi/filterbysize.md
        - PixelMaskCollection: api/roi/pixelmaskcollection.md
        - TIV and amplitude lung space: api/roi/tivlungspace.md
        - Watershed lung space: api/roi/watershed.md
      - api/parameters.md
      - api/categories.md
      - api/mixins.md
      - Plotting:
        - Rate Detection: api/plotting/rate_detection.md
        - PixelMap: api/plotting/pixelmap.md
        - Filter: api/plotting/filter.md
  - About:
      - Contributing: contributing_doc.md
      - Code of Conduct: code_of_conduct_doc.md
      - license_doc.md
      - team.md

extra:
  version:
    provider: mike

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      default_lang: "py"
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: ["docs", "."]

watch:
  - docs

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - exclude:
      glob:
        - __pycache__/*
  - autorefs
  - mkdocs-jupyter:
      ignore: ["**/ignore/*.ipynb", "**/ignore/*.py"]
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
          options:
            members_order: source
            inherited_members: true
            filters: ["!^_"]
            merge_init_into_class: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_submodules: true
            heading_level: 2
            show_bases: false
            show_source: false
            docstring_section_style: spacy
            line_length: 80

extra_css:
  - css/material.css
