name: Build package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "**.ipynb"
    branches:
      - main
      - develop

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: Build for ${{ matrix.python-version }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Connect to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: drcandacemakedamoore
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests in Container
        run: >
          docker run
          --rm
          -v ${{ github.workspace }}:/ci
          -e EIT_PROCESSING_TEST_DATA=/eitprocessing
          ghcr.io/eit-alive/eittestdata:latest
          sh -c 'set -xe ;
            cd /ci ;
            python${{ matrix.python-version }} -m pip install ".[dev,publishing]" ;
            pytest -v ;
            python${{ matrix.python-version }} -m build'

  coveralls:
    if: github.event.pull_request.draft == false
    name: Coveralls build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Connect to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: drcandacemakedamoore
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests in Container
        run: >
          docker run
          --rm
          -v ${{ github.workspace }}:/ci
          -e EIT_PROCESSING_TEST_DATA=/eitprocessing
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          -e COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}
          -e COVERALLS_FLAG_NAME=python-${{ matrix.python-version }}
          ghcr.io/eit-alive/eittestdata:latest
          sh -c 'set -xe ;
            cd /ci ;
            python${{ matrix.python-version }} -m pip install --upgrade pip setuptools ;
            python${{ matrix.python-version }} -m pip install ".[dev,publishing]" ;
            pytest --cov --cov-append --cov-report xml --cov-report term --cov-report html ;
            coveralls --service=github ;
            python${{ matrix.python-version }} -m build'
