name: Build package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "**.ipynb"
    branches:
      - main
      - develop

jobs:
  test_and_build:
    if: github.event.pull_request.draft == false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: Build for ${{ matrix.python-version }}, ${{ matrix.os }}
    env: 
      EIT_PROCESSING_TEST_DATA: ${{ github.workspace }}/../eitprocessing_data/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Connect to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: psomhorst
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract data from image
        uses: shrink/actions-docker-extract@v3
        with: 
          image: ghcr.io/eit-alive/eittestdata:latest
          destination: $EIT_PROCESSING_TEST_DATA
          path: /eitprocessing/.
      - name: Install eitprocessing
        run: python3 -m pip install ".[dev,publishing]"
      - name: Run pytest
        run: pytest -v
      - name: Build eitprocessing
        run: python3 -m build
