name: coveralls

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Coveralls
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-python-and-package
      - name: Run unit tests with coverage
        run: pytest --cov --cov-append --cov-report xml --cov-report term --cov-report html
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: python-${{ matrix.version }}
        run: |
          coveralls --service=github