name: Build Documentation
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Upgrade pip and install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install .[docs]
      - name: Build documentation
        run: mkdocs build
      - name: Deploy documentation
        run: mkdocs gh-deploy
