name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - "**.ipynb"
    branches:
      - main

jobs:
  lint:
    if: github.event.pull_request.draft == false
    name: Linting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -l {0}
        run: |
          which python3
          python3 --version
      - name: Check linting and formatting using ruff
        run: |
          python3 -m pip install ruff
          ruff check || echo "Please ensure you have the latest version of ruff (`ruff -V`) installed locally."
          ruff format --check || echo "Please ensure you have the latest version of ruff (`ruff -V`) installed locally."
