name: Build and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    name: Build universal wheel and source distribution
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Connect to Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: drcandacemakedamoore
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests in Container
        run: >
          docker run
          --rm
          -v ${{ github.workspace }}:/ci
          -e EIT_PROCESSING_TEST_DATA=/eitprocessing
          ghcr.io/eit-alive/eittestdata:latest
          sh -c 'set -xe ;
            cd /ci ;
            python -m pip install ".[dev,publishing]"'

  upload_test_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN_ALIVE }}
          repository_url: https://test.pypi.org/legacy/

  upload_pypi:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN_ALIVE }}
